Constraints_for_each_player = cell(1,data.producer_num);
for i = 1:data.producer_num
    Constraints_for_each_player{1,i} = [];
    for g = 1:data.G_num
        if B_G_producer(i,g) == 1
            if ismember(i,data.strategy_producer_id)
%                 Constraints_for_each_player{1,i} = ...
%                     [Constraints_for_each_player{1,i};
%                     b_g_t(g,:) >= 0*data.G(g,4)];
%                 Constraints_for_each_player{1,i} = ...
%                     [Constraints_for_each_player{1,i};
%                     b_g_t(g,:) <= 2*data.G(g,4)];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    b_g_t(g,:) >= 0];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    b_g_t(g,:) <= 16];
            else
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    b_g_t(g,:) == data.G(g,4)];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    u_P_g_RO(g,1) == 0];
            end

            % 非线性函数线性化
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_g_t_rou_G(g,:) >= 0];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_g_t_rou_G(g,:) <= u_g_t_rou_G(g,:)*M];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_g_t_rou_G(g,:) >= -lambda_t(1,:)-...
                B_G_NODE(:,g)'*PTDF'*mu_f_t_max(:,:)+...
                B_G_NODE(:,g)'*PTDF'*mu_f_t_min(:,:)-data.K];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_g_t_rou_G(g,:) <= -lambda_t(1,:)-...
                B_G_NODE(:,g)'*PTDF'*mu_f_t_max(:,:)+...
                B_G_NODE(:,g)'*PTDF'*mu_f_t_min(:,:)-data.K+...
                (1-u_g_t_rou_G(g,:))*M];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                z_g_t_rou_G(g,:) >= 0];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                z_g_t_rou_G(g,:) <= u_P_g_RO(g,1)*M];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                z_g_t_rou_G(g,:) - y_g_t_rou_G(g,:) >= ...
                -(1-u_P_g_RO(g,1))*M];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                z_g_t_rou_G(g,:) - y_g_t_rou_G(g,:) <= ...
                (1-u_P_g_RO(g,1))*M];
        end
    end
    clear g;
    for e = 1:data.E_num
        if B_E_producer(i,e) == 1
            if ismember(i,data.strategy_producer_id)
%                 Constraints_for_each_player{1,i} = ...
%                     [Constraints_for_each_player{1,i};
%                     b_e_t(e,:) >= 0*data.E(e,4)];
%                 Constraints_for_each_player{1,i} = ...
%                     [Constraints_for_each_player{1,i};
%                     b_e_t(e,:) <= 2*data.E(e,4)];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    b_e_t(e,:) >= 0];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    b_e_t(e,:) <= 16];
            else
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    b_e_t(e,:) == data.E(e,4)];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    u_P_e_RO(e,1) == 0];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    u_P_e_invest(e,:) == 0];
            end

            % 非线性函数线性化
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_e_t_rou_E(e,:) >= 0];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_e_t_rou_E(e,:) <= u_e_t_rou_E(e,:)*M];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_e_t_rou_E(e,:) >= -lambda_t(1,:)-...
                B_E_NODE(:,e)'*PTDF'*mu_f_t_max(:,:)+...
                B_E_NODE(:,e)'*PTDF'*mu_f_t_min(:,:)-data.K];
            Constraints_for_each_player{1,i} = ...
                [Constraints_for_each_player{1,i};
                y_e_t_rou_E(e,:) <= -lambda_t(1,:)-...
                B_E_NODE(:,e)'*PTDF'*mu_f_t_max(:,:)+...
                B_E_NODE(:,e)'*PTDF'*mu_f_t_min(:,:)-data.K+...
                (1-u_e_t_rou_E(e,:))*M];
            for k = 1:data.E_discrete_num
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    u_e_k_RO_invest(e,k) <= u_P_e_invest(e,k)];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    u_e_k_RO_invest(e,k) <= u_P_e_RO(e,1)];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    u_e_k_RO_invest(e,k) >= u_P_e_RO(e,1)+u_P_e_invest(e,k)-1];

                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    z_e_t_k_rou_E(e,:,k) >= 0];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    z_e_t_k_rou_E(e,:,k) <= u_e_k_RO_invest(e,k)*M];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    z_e_t_k_rou_E(e,:,k) - y_e_t_rou_E(e,:) >= ...
                    -(1-u_e_k_RO_invest(e,k))*M];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};
                    z_e_t_k_rou_E(e,:,k) - y_e_t_rou_E(e,:) <= ...
                    (1-u_e_k_RO_invest(e,k))*M];
            end
        end
        for t = 1:data.T_num
            for k = 1:data.E_discrete_num
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};w_e_t_k_E(e,t,k) >= 0];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};w_e_t_k_E(e,t,k) <= M*u_P_e_invest(e,k)];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};w_e_t_k_E(e,t,k) >= ...
                    tao_e_t_max(e,t)-M*(1-u_P_e_invest(e,k))];
                Constraints_for_each_player{1,i} = ...
                    [Constraints_for_each_player{1,i};w_e_t_k_E(e,t,k) <= ...
                    tao_e_t_max(e,t)+M*(1-u_P_e_invest(e,k))];
            end
        end
    end
    clear e;
end
clear i t q;