Constraints_clearing = [];
Constraints_clearing = [Constraints_clearing;(sum(P_g_t,1) + sum(P_e_t,1) ...
    == sum(P_d_t,1)):'LL'];
Constraints_clearing = [Constraints_clearing;0 <= P_g_t];
Constraints_clearing = [Constraints_clearing;P_g_t <= data.G(:,5)*ones(1,data.T_num)];
Constraints_clearing = [Constraints_clearing;0 <= P_e_t];
Constraints_clearing = [Constraints_clearing;P_e_t <= ...
    (sum(u_P_e_invest_new,2).*data.E(:,5)/data.E_discrete_num)*ones(1,data.T_num)];
Constraints_clearing = [Constraints_clearing;0 <= P_d_t];
Constraints_clearing = [Constraints_clearing;P_d_t <= data.D_P];
Constraints_clearing = [Constraints_clearing;(-data.branch(data.congestion_id,4)*ones(1,data.T_num) <= ...
    PTDF*(B_G_NODE*P_g_t+B_E_NODE*P_e_t-B_D_NODE*P_d_t)):'MM1'];
Constraints_clearing = [Constraints_clearing;(PTDF*(B_G_NODE*P_g_t+B_E_NODE*P_e_t-...
    B_D_NODE*P_d_t) <= data.branch(data.congestion_id,4)*ones(1,data.T_num)):'MM2'];
Obj_clearing2 = sum(sum(b_g_t_new.*P_g_t)) + ...
    sum(sum(b_e_t_new.*P_e_t)) - sum(sum(data.voll*P_d_t));
ops2 = sdpsettings('solver','gurobi','verbose',0);
optimize(Constraints_clearing,Obj_clearing2/10000,ops2);
lambda = dual(Constraints_clearing('LL'));
mu_min = reshape(dual(Constraints_clearing('MM1')),data.congestion_num,data.T_num);
mu_max = reshape(dual(Constraints_clearing('MM2')),data.congestion_num,data.T_num);
LMP = -lambda + PTDF'*(mu_min - mu_max);
P_g_t_new = value(P_g_t);
P_e_t_new = value(P_e_t);
P_d_t_new = value(P_d_t);
SM_income = B_G_producer*(B_G_NODE'*LMP.*P_g_t_new)*data.dT' + ...
    B_E_producer*(B_E_NODE'*LMP.*P_e_t_new)*data.dT';
fuel_cost = -B_G_producer*(data.G(:,4)*ones(1,data.T_num).*P_g_t_new)*data.dT'-...
    B_E_producer*(data.E(:,4)*ones(1,data.T_num).*P_e_t_new)*data.dT';
invest_cost = -B_E_producer*(data.E(:,6).*sum(u_P_e_invest_new.*...
    (data.E(:,5)/data.E_discrete_num*ones(1,data.E_discrete_num)),2));
RO_income = data.RO_rou*B_G_producer*(u_P_g_RO_new.*data.G(:,5)) + ...
    data.RO_rou*B_E_producer*(u_P_e_RO_new.*sum(u_P_e_invest_new.*...
    (data.E(:,5)/data.E_discrete_num*ones(1,data.E_discrete_num)),2));
RO_return = -B_G_producer*(max(B_G_NODE'*LMP-data.K,0).*...
    ((u_P_g_RO_new.*data.G(:,5))*ones(1,data.T_num)))*data.dT' - ...
    B_E_producer*(max(B_E_NODE'*LMP-data.K,0).*...
    ((u_P_e_RO_new.*sum(u_P_e_invest_new.*...
    (data.E(:,5)/data.E_discrete_num*ones(1,data.E_discrete_num)),2))*...
    ones(1,data.T_num)))*data.dT';
producer_total_income = SM_income + fuel_cost + RO_income + RO_return + invest_cost;
rou_U = sum(([B_G_NODE,B_E_NODE]'*LMP).*[P_g_t_new;P_e_t_new]./...
    sum([P_g_t_new;P_e_t_new],1),1);
D_buy = rou_U.*P_d_t_new*data.dT';
D_OF = sum(RO_income)*(P_d_t_new)*data.dT'/sum((P_d_t_new)*data.dT');
D_RE = sum(RO_return)*(P_d_t_new)*data.dT'/sum((P_d_t_new)*data.dT');
D_voll = data.voll*(data.D_P-P_d_t_new)*data.dT';
D_total_cost = D_buy + D_OF + D_RE + D_voll;